default_stages: [pre-commit]
default_language_version:
    python: python3
ci:
    skip: [ruff, ruff-format]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        stages: [manual]
    -   id: check-ast
    -   id: check-json
    -   id: check-xml
    -   id: mixed-line-ending
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
        stages: [manual]
    -   id: fix-byte-order-marker
        stages: [manual]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
    -   id: ruff
        args: [ --fix ]
        stages: [manual]
    -   id: ruff-format
        stages: [manual]
